CONST = {
	SHOW_GLOBAL_LOADING: "SHOW_GLOBAL_LOADING",
	HIDE_GLOBAL_LOADING: "HIDE_GLOBAL_LOADING",
    LISTS_READY: "LISTS_READY",
    TASKS_READY: "TASKS_READY",
    ADD_TASK: "ADD_TASK",
    ADD_LIST: "ADD_LIST",
    DELETE_TASK: "DELETE_TASK",
    TOGGLE_LISTS_NAV: "TOGGLE_LISTS_NAV",
    SHOW_LIST_DIALOG: "SHOW_LIST_DIALOG",
    SHOW_TASK_DIALOG: "SHOW_TASK_DIALOG",
};
